### ISSUE TITLE
oxygen plugin: invalid translitertor ID

### ISSUE THREAD

**Issue by lueck** [SCDH/icu-xpath-bindings#1]
When using in oXygen, ICU4J does not find the transliterators (and normalizers). When firing a the example transformation in `doc/transliterate.xsl` I get the following error:

```
illegal transliterator ID for icu:transliterate(..., "NFD; [:nonspacing mark:] Remove; NFC"): Invalid ID "NFD; [:nonspacing mark:] Remove; NFC"
```

Running the same transformation outside of oxygen with Saxon command line interface, works fine.

**Comment by lueck** [comment]
The reason seems to be some interference with the classes installed in oxygen. The older version of ICU4J in the classpath (4.2?, see `OXYGEN_INSTALL_DIR/lib/icu4j.jar`) seems to be used.

Comparison of the stack traces for a definitively unknown transliterator (`Bagle`) indicates, that the problem is interference with oxygen resources:

Here's the stacktrace from the command line:

```
[main] ERROR de.wwu.scdh.xpath.icu.text.Transliterate - illegal transliterator ID: Illegal ID Bagle
{}
java.lang.IllegalArgumentException: Illegal ID Bagle
        at com.ibm.icu.text.TransliteratorIDParser.instantiateList(TransliteratorIDParser.java:439)
        at com.ibm.icu.text.Transliterator.getInstance(Transliterator.java:1603)
        at com.ibm.icu.text.Transliterator.getInstance(Transliterator.java:1576)
        at de.wwu.scdh.xpath.icu.text.Transliterate$1.call(Transliterate.java:79)
        at net.sf.saxon.functions.IntegratedFunctionCall.iterate(IntegratedFunctionCall.java:293)
        at net.sf.saxon.expr.Expression.process(Expression.java:948)
        at net.sf.saxon.expr.instruct.ValueOf.processLeavingTail(ValueOf.java:345)
        at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:392)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:551)
        at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:72)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:524)
        at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:72)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:524)
        at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:685)
        at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:421)
        at net.sf.saxon.s9api.Xslt30Transformer.applyTemplates(Xslt30Transformer.java:301)
        at net.sf.saxon.Transform.processFile(Transform.java:1394)
        at net.sf.saxon.Transform.doTransform(Transform.java:869)
        at net.sf.saxon.Transform.main(Transform.java:81)
``` 

Here's the stacktrace when running the transformation inside oxygen (start oxygen from the commandline and you will see it printed there):

```
08:27:37 951508 ERROR [ Transformation Performer ] de.wwu.scdh.xpath.icu.text.Transliterate - illegal transliterator ID: Invalid ID "Bagle"
{}
java.lang.IllegalArgumentException: Invalid ID "Bagle"
        at com.ibm.icu.text.Transliterator.getInstance(Transliterator.java:1600)
        at com.ibm.icu.text.Transliterator.getInstance(Transliterator.java:1576)
        at de.wwu.scdh.xpath.icu.text.Transliterate$1.call(Transliterate.java:79)
        at net.sf.saxon.functions.IntegratedFunctionCall.iterate(IntegratedFunctionCall.java:293)
        at net.sf.saxon.expr.Expression.process(Expression.java:949)
        at net.sf.saxon.expr.instruct.ValueOf.processLeavingTail(ValueOf.java:343)
        at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:393)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:568)
        at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:72)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:530)
        at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:72)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:530)
        at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:661)
        at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:360)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:349)
        at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:74)
        at ro.sync.exml.editor.xmleditor.hc.yze(Unknown Source)
        at ro.sync.exml.editor.xmleditor.hc.zaf(Unknown Source)
        at ro.sync.exml.editor.xmleditor.hc.wze(Unknown Source)
        at ro.sync.exml.editor.xmleditor.hc.uye(Unknown Source)
        at ro.sync.exml.editor.xmleditor.hc.eze(Unknown Source)
        at ro.sync.exml.editor.xmleditor.hc$4.zlk(Unknown Source)
        at ro.sync.ui.application.lb.run(Unknown Source)
```

So there is an other `com.ibm.icu.text.Transliterator` Java source file, i.e. an other ICU4J version, in force in oxygen.
